### ISSUE TITLE
Report issues page bug 

### ISSUE THREAD

**Issue by Roshan-Mirchandani** [PaulDavidTucker/EECSPlus#3]
when reporting an issue, the status column stays empty in the record when it should be pending

**Comment by PaulDavidTucker** [comment]
LMAO 

![image](https://user-images.githubusercontent.com/94861347/230324703-7990c314-3ecd-4c6a-8817-c386a29aa297.png)

SQL db will only accept enums with const literals of the incorrect spelling, have since been updated.

![image](https://user-images.githubusercontent.com/94861347/230325291-4dbda076-4fc6-457b-8c68-d5d6ab17757e.png)
